kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: greeting
  commands:
  - pwd
  - whoami
  - cd /root/webhook
  - git pull origin master

node:
  tag: host_docker

