kind: pipeline
type: exec
name: exec-update-dev

steps:
- name: git clone
  # image: artifactory.aecadmin.ir/ravan/alpine
  # image: alpine
  commands:
  - echo "echo master branch"
node:
  tag: host_docker
trigger:
  branch:
  - master
  event:
  - push

---
kind: pipeline
type: docker
name: docker-update-dev
steps:
- name: say hello
  # image: artifactory.aecadmin.ir/ravan/alpine
  image: alpine
  commands:
  - echo "hello dev branch"
node:
  tag: host_docker
trigger:
  branch:
  - dev

---
kind: pipeline
type: docker
name: docker-promote-dev

steps:
- name: promote 
  # image: artifactory.aecadmin.ir/ravan/alpine
  image: alpine
  commands:
  - echo "hello dev branch for promotion"
node:
  tag: host_xvision
trigger:
  branch:
  - dev
  event:
  - promote
  target:
  - prod
