kind: pipeline
type: exec
name: exec-git-clone

steps:
- name: runner-test
  # image: artifactory.aecadmin.ir/ravan/alpine
  image: alpine
  commands:
  - echo "echo master branch"

node:
  tag: host_docker
trigger:
  branch:
  - master
  event:
  - push

---
kind: pipeline
type: docker
name: docker-echo

steps:
- name: runner-test
  # image: artifactory.aecadmin.ir/ravan/alpine
  image: alpine
  commands:
  - echo "hello dev branch"

node:
  tag: host_docker
trigger:
  branch:
  - dev
  event:
  - push
