kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: bash:4.4
  pull: never
  commands:
  - $PWD/script.sh

node:
  tag: aectest-docker
trigger:
  branch:
  - master
  event:
  - push
